apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: filepizza
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 31337
    protocol: TCP
  selector:
    app: filepizza
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: filepizza
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: file.pizza
    http:
      paths:
      - path: /
        backend:
          serviceName: filepizza
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: filepizza
spec:
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: filepizza
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: filepizza
        image: kern/filepizza:1.0.6
        ports:
        - containerPort: 80
        env:
        - name: FORCE_SSL
          value: "true"
        - name: TWILIO_SID
          valueFrom:
            secretKeyRef:
              name: twilio
              key: sid
        - name: TWILIO_TOKEN
          valueFrom:
            secretKeyRef:
              name: twilio
              key: token
