apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: kernio
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: kernio
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: kernio
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: kern.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kernio
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: kernio
spec:
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: kernio
    spec:
      containers:
      - name: kernio
        image: kern/io:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
